/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScannerScanRouteImport } from './routes/api/scanner/scan'
import { Route as ApiScannerDefaultMarketRouteImport } from './routes/api/scanner/default-market'
import { Route as ApiPredictorPredictRouteImport } from './routes/api/predictor/predict'
import { Route as ApiPredictorPerformanceRouteImport } from './routes/api/predictor/performance'
import { Route as ApiPredictorFixturesRouteImport } from './routes/api/predictor/fixtures'
import { Route as ApiPredictorContextRouteImport } from './routes/api/predictor/context'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScannerScanRoute = ApiScannerScanRouteImport.update({
  id: '/api/scanner/scan',
  path: '/api/scanner/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScannerDefaultMarketRoute = ApiScannerDefaultMarketRouteImport.update({
  id: '/api/scanner/default-market',
  path: '/api/scanner/default-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorPredictRoute = ApiPredictorPredictRouteImport.update({
  id: '/api/predictor/predict',
  path: '/api/predictor/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorPerformanceRoute = ApiPredictorPerformanceRouteImport.update({
  id: '/api/predictor/performance',
  path: '/api/predictor/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorFixturesRoute = ApiPredictorFixturesRouteImport.update({
  id: '/api/predictor/fixtures',
  path: '/api/predictor/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorContextRoute = ApiPredictorContextRouteImport.update({
  id: '/api/predictor/context',
  path: '/api/predictor/context',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/predictor'
    | '/scanner'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/predictor'
    | '/scanner'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
  id:
    | '__root__'
    | '/'
    | '/predictor'
    | '/scanner'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PredictorRoute: typeof PredictorRoute
  ScannerRoute: typeof ScannerRoute
  ApiPredictorContextRoute: typeof ApiPredictorContextRoute
  ApiPredictorFixturesRoute: typeof ApiPredictorFixturesRoute
  ApiPredictorPerformanceRoute: typeof ApiPredictorPerformanceRoute
  ApiPredictorPredictRoute: typeof ApiPredictorPredictRoute
  ApiScannerDefaultMarketRoute: typeof ApiScannerDefaultMarketRoute
  ApiScannerScanRoute: typeof ApiScannerScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scanner/scan': {
      id: '/api/scanner/scan'
      path: '/api/scanner/scan'
      fullPath: '/api/scanner/scan'
      preLoaderRoute: typeof ApiScannerScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scanner/default-market': {
      id: '/api/scanner/default-market'
      path: '/api/scanner/default-market'
      fullPath: '/api/scanner/default-market'
      preLoaderRoute: typeof ApiScannerDefaultMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/predict': {
      id: '/api/predictor/predict'
      path: '/api/predictor/predict'
      fullPath: '/api/predictor/predict'
      preLoaderRoute: typeof ApiPredictorPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/performance': {
      id: '/api/predictor/performance'
      path: '/api/predictor/performance'
      fullPath: '/api/predictor/performance'
      preLoaderRoute: typeof ApiPredictorPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/fixtures': {
      id: '/api/predictor/fixtures'
      path: '/api/predictor/fixtures'
      fullPath: '/api/predictor/fixtures'
      preLoaderRoute: typeof ApiPredictorFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/context': {
      id: '/api/predictor/context'
      path: '/api/predictor/context'
      fullPath: '/api/predictor/context'
      preLoaderRoute: typeof ApiPredictorContextRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PredictorRoute: PredictorRoute,
  ScannerRoute: ScannerRoute,
  ApiPredictorContextRoute: ApiPredictorContextRoute,
  ApiPredictorFixturesRoute: ApiPredictorFixturesRoute,
  ApiPredictorPerformanceRoute: ApiPredictorPerformanceRoute,
  ApiPredictorPredictRoute: ApiPredictorPredictRoute,
  ApiScannerDefaultMarketRoute: ApiScannerDefaultMarketRoute,
  ApiScannerScanRoute: ApiScannerScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
