/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as ObserverRouteImport } from './routes/observer'
import { Route as ElevenOverRouteImport } from './routes/eleven-over'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScannerScanRouteImport } from './routes/api/scanner/scan'
import { Route as ApiScannerDefaultMarketRouteImport } from './routes/api/scanner/default-market'
import { Route as ApiPredictorPredictRouteImport } from './routes/api/predictor/predict'
import { Route as ApiPredictorPerformanceRouteImport } from './routes/api/predictor/performance'
import { Route as ApiPredictorFixturesRouteImport } from './routes/api/predictor/fixtures'
import { Route as ApiPredictorContextRouteImport } from './routes/api/predictor/context'
import { Route as ApiObserverReadyRouteImport } from './routes/api/observer/ready'
import { Route as ApiObserverLiveModelRouteImport } from './routes/api/observer/live-model'
import { Route as ApiObserverFixturesRouteImport } from './routes/api/observer/fixtures'
import { Route as ApiObserverBallStateShadowRouteImport } from './routes/api/observer/ball-state-shadow'
import { Route as ApiObserverLiveModelSignalsRouteImport } from './routes/api/observer/live-model/signals'
import { Route as ApiObserverLiveModelHistoryRouteImport } from './routes/api/observer/live-model/history'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserverRoute = ObserverRouteImport.update({
  id: '/observer',
  path: '/observer',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevenOverRoute = ElevenOverRouteImport.update({
  id: '/eleven-over',
  path: '/eleven-over',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScannerScanRoute = ApiScannerScanRouteImport.update({
  id: '/api/scanner/scan',
  path: '/api/scanner/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScannerDefaultMarketRoute = ApiScannerDefaultMarketRouteImport.update({
  id: '/api/scanner/default-market',
  path: '/api/scanner/default-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorPredictRoute = ApiPredictorPredictRouteImport.update({
  id: '/api/predictor/predict',
  path: '/api/predictor/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorPerformanceRoute = ApiPredictorPerformanceRouteImport.update({
  id: '/api/predictor/performance',
  path: '/api/predictor/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorFixturesRoute = ApiPredictorFixturesRouteImport.update({
  id: '/api/predictor/fixtures',
  path: '/api/predictor/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictorContextRoute = ApiPredictorContextRouteImport.update({
  id: '/api/predictor/context',
  path: '/api/predictor/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObserverReadyRoute = ApiObserverReadyRouteImport.update({
  id: '/api/observer/ready',
  path: '/api/observer/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObserverLiveModelRoute = ApiObserverLiveModelRouteImport.update({
  id: '/api/observer/live-model',
  path: '/api/observer/live-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObserverFixturesRoute = ApiObserverFixturesRouteImport.update({
  id: '/api/observer/fixtures',
  path: '/api/observer/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObserverBallStateShadowRoute =
  ApiObserverBallStateShadowRouteImport.update({
    id: '/api/observer/ball-state-shadow',
    path: '/api/observer/ball-state-shadow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObserverLiveModelSignalsRoute =
  ApiObserverLiveModelSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => ApiObserverLiveModelRoute,
  } as any)
const ApiObserverLiveModelHistoryRoute =
  ApiObserverLiveModelHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiObserverLiveModelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eleven-over': typeof ElevenOverRoute
  '/observer': typeof ObserverRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/observer/ball-state-shadow': typeof ApiObserverBallStateShadowRoute
  '/api/observer/fixtures': typeof ApiObserverFixturesRoute
  '/api/observer/live-model': typeof ApiObserverLiveModelRouteWithChildren
  '/api/observer/ready': typeof ApiObserverReadyRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
  '/api/observer/live-model/history': typeof ApiObserverLiveModelHistoryRoute
  '/api/observer/live-model/signals': typeof ApiObserverLiveModelSignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eleven-over': typeof ElevenOverRoute
  '/observer': typeof ObserverRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/observer/ball-state-shadow': typeof ApiObserverBallStateShadowRoute
  '/api/observer/fixtures': typeof ApiObserverFixturesRoute
  '/api/observer/live-model': typeof ApiObserverLiveModelRouteWithChildren
  '/api/observer/ready': typeof ApiObserverReadyRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
  '/api/observer/live-model/history': typeof ApiObserverLiveModelHistoryRoute
  '/api/observer/live-model/signals': typeof ApiObserverLiveModelSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eleven-over': typeof ElevenOverRoute
  '/observer': typeof ObserverRoute
  '/predictor': typeof PredictorRoute
  '/scanner': typeof ScannerRoute
  '/api/observer/ball-state-shadow': typeof ApiObserverBallStateShadowRoute
  '/api/observer/fixtures': typeof ApiObserverFixturesRoute
  '/api/observer/live-model': typeof ApiObserverLiveModelRouteWithChildren
  '/api/observer/ready': typeof ApiObserverReadyRoute
  '/api/predictor/context': typeof ApiPredictorContextRoute
  '/api/predictor/fixtures': typeof ApiPredictorFixturesRoute
  '/api/predictor/performance': typeof ApiPredictorPerformanceRoute
  '/api/predictor/predict': typeof ApiPredictorPredictRoute
  '/api/scanner/default-market': typeof ApiScannerDefaultMarketRoute
  '/api/scanner/scan': typeof ApiScannerScanRoute
  '/api/observer/live-model/history': typeof ApiObserverLiveModelHistoryRoute
  '/api/observer/live-model/signals': typeof ApiObserverLiveModelSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eleven-over'
    | '/observer'
    | '/predictor'
    | '/scanner'
    | '/api/observer/ball-state-shadow'
    | '/api/observer/fixtures'
    | '/api/observer/live-model'
    | '/api/observer/ready'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
    | '/api/observer/live-model/history'
    | '/api/observer/live-model/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eleven-over'
    | '/observer'
    | '/predictor'
    | '/scanner'
    | '/api/observer/ball-state-shadow'
    | '/api/observer/fixtures'
    | '/api/observer/live-model'
    | '/api/observer/ready'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
    | '/api/observer/live-model/history'
    | '/api/observer/live-model/signals'
  id:
    | '__root__'
    | '/'
    | '/eleven-over'
    | '/observer'
    | '/predictor'
    | '/scanner'
    | '/api/observer/ball-state-shadow'
    | '/api/observer/fixtures'
    | '/api/observer/live-model'
    | '/api/observer/ready'
    | '/api/predictor/context'
    | '/api/predictor/fixtures'
    | '/api/predictor/performance'
    | '/api/predictor/predict'
    | '/api/scanner/default-market'
    | '/api/scanner/scan'
    | '/api/observer/live-model/history'
    | '/api/observer/live-model/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElevenOverRoute: typeof ElevenOverRoute
  ObserverRoute: typeof ObserverRoute
  PredictorRoute: typeof PredictorRoute
  ScannerRoute: typeof ScannerRoute
  ApiObserverBallStateShadowRoute: typeof ApiObserverBallStateShadowRoute
  ApiObserverFixturesRoute: typeof ApiObserverFixturesRoute
  ApiObserverLiveModelRoute: typeof ApiObserverLiveModelRouteWithChildren
  ApiObserverReadyRoute: typeof ApiObserverReadyRoute
  ApiPredictorContextRoute: typeof ApiPredictorContextRoute
  ApiPredictorFixturesRoute: typeof ApiPredictorFixturesRoute
  ApiPredictorPerformanceRoute: typeof ApiPredictorPerformanceRoute
  ApiPredictorPredictRoute: typeof ApiPredictorPredictRoute
  ApiScannerDefaultMarketRoute: typeof ApiScannerDefaultMarketRoute
  ApiScannerScanRoute: typeof ApiScannerScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observer': {
      id: '/observer'
      path: '/observer'
      fullPath: '/observer'
      preLoaderRoute: typeof ObserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleven-over': {
      id: '/eleven-over'
      path: '/eleven-over'
      fullPath: '/eleven-over'
      preLoaderRoute: typeof ElevenOverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scanner/scan': {
      id: '/api/scanner/scan'
      path: '/api/scanner/scan'
      fullPath: '/api/scanner/scan'
      preLoaderRoute: typeof ApiScannerScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scanner/default-market': {
      id: '/api/scanner/default-market'
      path: '/api/scanner/default-market'
      fullPath: '/api/scanner/default-market'
      preLoaderRoute: typeof ApiScannerDefaultMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/predict': {
      id: '/api/predictor/predict'
      path: '/api/predictor/predict'
      fullPath: '/api/predictor/predict'
      preLoaderRoute: typeof ApiPredictorPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/performance': {
      id: '/api/predictor/performance'
      path: '/api/predictor/performance'
      fullPath: '/api/predictor/performance'
      preLoaderRoute: typeof ApiPredictorPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/fixtures': {
      id: '/api/predictor/fixtures'
      path: '/api/predictor/fixtures'
      fullPath: '/api/predictor/fixtures'
      preLoaderRoute: typeof ApiPredictorFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictor/context': {
      id: '/api/predictor/context'
      path: '/api/predictor/context'
      fullPath: '/api/predictor/context'
      preLoaderRoute: typeof ApiPredictorContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observer/ready': {
      id: '/api/observer/ready'
      path: '/api/observer/ready'
      fullPath: '/api/observer/ready'
      preLoaderRoute: typeof ApiObserverReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observer/live-model': {
      id: '/api/observer/live-model'
      path: '/api/observer/live-model'
      fullPath: '/api/observer/live-model'
      preLoaderRoute: typeof ApiObserverLiveModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observer/fixtures': {
      id: '/api/observer/fixtures'
      path: '/api/observer/fixtures'
      fullPath: '/api/observer/fixtures'
      preLoaderRoute: typeof ApiObserverFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observer/ball-state-shadow': {
      id: '/api/observer/ball-state-shadow'
      path: '/api/observer/ball-state-shadow'
      fullPath: '/api/observer/ball-state-shadow'
      preLoaderRoute: typeof ApiObserverBallStateShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observer/live-model/signals': {
      id: '/api/observer/live-model/signals'
      path: '/signals'
      fullPath: '/api/observer/live-model/signals'
      preLoaderRoute: typeof ApiObserverLiveModelSignalsRouteImport
      parentRoute: typeof ApiObserverLiveModelRoute
    }
    '/api/observer/live-model/history': {
      id: '/api/observer/live-model/history'
      path: '/history'
      fullPath: '/api/observer/live-model/history'
      preLoaderRoute: typeof ApiObserverLiveModelHistoryRouteImport
      parentRoute: typeof ApiObserverLiveModelRoute
    }
  }
}

interface ApiObserverLiveModelRouteChildren {
  ApiObserverLiveModelHistoryRoute: typeof ApiObserverLiveModelHistoryRoute
  ApiObserverLiveModelSignalsRoute: typeof ApiObserverLiveModelSignalsRoute
}

const ApiObserverLiveModelRouteChildren: ApiObserverLiveModelRouteChildren = {
  ApiObserverLiveModelHistoryRoute: ApiObserverLiveModelHistoryRoute,
  ApiObserverLiveModelSignalsRoute: ApiObserverLiveModelSignalsRoute,
}

const ApiObserverLiveModelRouteWithChildren =
  ApiObserverLiveModelRoute._addFileChildren(ApiObserverLiveModelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElevenOverRoute: ElevenOverRoute,
  ObserverRoute: ObserverRoute,
  PredictorRoute: PredictorRoute,
  ScannerRoute: ScannerRoute,
  ApiObserverBallStateShadowRoute: ApiObserverBallStateShadowRoute,
  ApiObserverFixturesRoute: ApiObserverFixturesRoute,
  ApiObserverLiveModelRoute: ApiObserverLiveModelRouteWithChildren,
  ApiObserverReadyRoute: ApiObserverReadyRoute,
  ApiPredictorContextRoute: ApiPredictorContextRoute,
  ApiPredictorFixturesRoute: ApiPredictorFixturesRoute,
  ApiPredictorPerformanceRoute: ApiPredictorPerformanceRoute,
  ApiPredictorPredictRoute: ApiPredictorPredictRoute,
  ApiScannerDefaultMarketRoute: ApiScannerDefaultMarketRoute,
  ApiScannerScanRoute: ApiScannerScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
